name: 🚀 Deploy RomaChatHandler to AWS

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "requirements.txt"
      - ".github/workflows/deploy_lambda.yml"

jobs:
  deploy:
    name: Deploy Roma Lambda
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Install Dependencies & Package Lambda
        run: |
          mkdir -p package

          # ✅ Install dependencies with Lambda-compatible binaries
          pip install --platform manylinux2014_x86_64 \
                      --target package/ \
                      --implementation cp \
                      --python-version 3.11 \
                      --only-binary=:all: \
                      --upgrade -r requirements.txt

          # ✅ Copy the full src folder (preserve module structure)
          cp -r src package/src

          # ✅ Copy the Lambda entrypoint to the root of ZIP
          cp src/lambda_chat_handler.py package/

          # ✅ Create zip
          cd package
          zip -r ../deployment.zip . -x "**/__pycache__/*" "*.git*"

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: 🚀 Deploy RomaChatHandler
        run: |
          aws lambda update-function-code \
            --function-name ${{ vars.LAMBDA_ROMA_HANDLER_NAME }} \
            --zip-file fileb://deployment.zip \
            --region ${{ vars.AWS_REGION }}

      - name: ✅ Deployment Complete
        run: echo "RomaChatHandler successfully deployed!"
